name: Release TBC Update # description of this workflow, can be anything you want

# triggers when pushing a tag
on:
  push:
    branches:
      - 'tbc-classic'
    tags:
      - '*-TBC'

env:
  # for github releases, this secret is automatically provided to the workflow
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release: # "release" is a job, you can name it anything you want
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: BigWigsMods/packager@master
        with:
          args: -g bcc
